# Generated by Django 4.2.25 on 2025-11-22 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_notificacionproblema_fecha_respuesta_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE pedidos ADD COLUMN estado_pago VARCHAR(20) DEFAULT 'Pago Completo' NOT NULL;",
            reverse_sql="ALTER TABLE pedidos DROP COLUMN estado_pago;",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE pedidos ADD COLUMN estado_pedido VARCHAR(20) DEFAULT 'Confirmado' NOT NULL;",
            reverse_sql="ALTER TABLE pedidos DROP COLUMN estado_pedido;",
        ),
    ]
