# Generated by Django 4.2.25 on 2025-11-24 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_estado_fields_sql'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pedidoproducto',
            options={'managed': True},
        ),
    ]
