# Generated by Django 4.2.25 on 2025-11-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_loteproducto_movimientolote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionReporte',
            fields=[
                ('idNotificacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('contenido_html', models.TextField()),
                ('tipo', models.CharField(default='DASHBOARD', max_length=50)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'notificaciones_reporte',
                'ordering': ['-fechaCreacion'],
                'managed': True,
            },
        ),
    ]
