# Generated by Django 4.2.25 on 2025-12-10 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_producto_precio_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=200, null=True)),
                ('telefono', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('idDistribuidor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDistribuidor', models.CharField(max_length=30, null=True)),
                ('contacto', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'distribuidores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DistribuidorProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idDistribuidor', models.IntegerField()),
                ('idProducto', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'distribuidor_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('idRepartidor', models.AutoField(primary_key=True, serialize=False)),
                ('nombreRepartidor', models.CharField(max_length=50, null=True)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('estado_turno', models.CharField(default='Disponible', max_length=20, null=True)),
            ],
            options={
                'db_table': 'repartidores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('id_rol', models.IntegerField()),
                ('idCliente', models.IntegerField(null=True)),
                ('fechaCreacion', models.DateTimeField()),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('direccion', models.CharField(max_length=50, null=True)),
                ('reset_token', models.CharField(max_length=255, null=True)),
                ('reset_token_expires', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoteProducto',
            fields=[
                ('idLote', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_lote', models.CharField(help_text='Código único del lote', max_length=100)),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cantidad_inicial', models.IntegerField(help_text='Cantidad inicial del lote')),
                ('cantidad_disponible', models.IntegerField(help_text='Cantidad disponible actual')),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_con_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'lotes_producto',
                'ordering': ['fecha_entrada'],
            },
        ),
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('idMensaje', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mensajes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NotificacionReporte',
            fields=[
                ('idNotificacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('contenido_html', models.TextField()),
                ('tipo', models.CharField(default='DASHBOARD', max_length=50)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'notificaciones_reporte',
                'ordering': ['-fechaCreacion'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('idProfile', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.IntegerField()),
                ('imagen', models.CharField(max_length=255, null=True)),
                ('descripcion', models.TextField(null=True)),
            ],
            options={
                'db_table': 'perfil',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pedidoproducto',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
        migrations.CreateModel(
            name='NotificacionProblema',
            fields=[
                ('idNotificacion', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='problemas_entrega/')),
                ('fechaReporte', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('respuesta_admin', models.TextField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('idPedido', models.ForeignKey(db_column='idPedido', on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
            ],
            options={
                'db_table': 'notificaciones_problema',
                'ordering': ['-fechaReporte'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovimientoProducto',
            fields=[
                ('idMovimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA_INICIAL', 'Entrada Inicial'), ('AJUSTE_MANUAL_ENTRADA', 'Ajuste Manual (Entrada)'), ('AJUSTE_MANUAL_SALIDA', 'Ajuste Manual (Salida)'), ('SALIDA_VENTA', 'Salida por Venta'), ('EN_PREPARACION_SALIDA', 'En Preparación (Apartado)'), ('PERDIDA_VENCIMIENTO', 'Pérdida por Vencimiento')], max_length=50)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, help_text='Costo por unidad para movimientos de entrada.', max_digits=10)),
                ('stock_anterior', models.IntegerField()),
                ('stock_nuevo', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('lote', models.CharField(blank=True, help_text='Código del lote del producto', max_length=100, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha de vencimiento del producto', null=True)),
                ('total_con_iva', models.DecimalField(blank=True, decimal_places=2, help_text='Total incluyendo IVA', max_digits=10, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, help_text='Valor del IVA (19%)', max_digits=10, null=True)),
                ('id_pedido', models.ForeignKey(blank=True, db_column='idPedido', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pedido')),
                ('lote_origen', models.ForeignKey(blank=True, help_text='Lote del cual salió el producto (para movimientos de salida)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.loteproducto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.producto')),
            ],
            options={
                'db_table': 'movimientos_producto',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoLote',
            fields=[
                ('idMovimientoLote', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(help_text='Cantidad tomada de este lote')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.loteproducto')),
                ('movimiento_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_lote', to='core.movimientoproducto')),
            ],
            options={
                'db_table': 'movimientos_lote',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='loteproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='core.producto'),
        ),
        migrations.CreateModel(
            name='ConfirmacionEntrega',
            fields=[
                ('idConfirmacion', models.AutoField(primary_key=True, serialize=False)),
                ('foto_entrega', models.ImageField(blank=True, null=True, upload_to='confirmaciones_entrega/')),
                ('calificacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_confirmacion', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmacion_entrega', to='core.pedido')),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.repartidor')),
            ],
            options={
                'db_table': 'confirmaciones_entrega',
            },
        ),
        migrations.AlterUniqueTogether(
            name='loteproducto',
            unique_together={('producto', 'codigo_lote')},
        ),
    ]
